client:
  ms-auth:
    url: http://localhost:8484
  ms-product:
    url: http://localhost:8181
  ms-payment:
    url: http://localhost:8282


redis:
  server:
    urls: redis://localhost:6379

rabbitmq:
  publisher-service:
    queue: NOTIFICATION_Q
    dlq: NOTIFICATION_DLQ