spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_order
    username: root
    password: password
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
#    drop-first: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false